// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package voz.auth.domain.Auth



object AuthProto extends _root_.com.trueaccord.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.com.trueaccord.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.wrappers.WrappersProto
  )
  lazy val messagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq(
    voz.auth.domain.Auth.TokenRequest,
    voz.auth.domain.Auth.ChildTokenRequest,
    voz.auth.domain.Auth.TokenReply
  )
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgpBdXRoLnByb3RvEg92b3ouYXV0aC5kb21haW4aHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVycy5wcm90byLjAgoMVG9rZW5SZ
  XF1ZXN0EhgKB3N1YmplY3QYASABKAlSB3N1YmplY3QSKQoEcm9sZRgCIAEoDjIVLnZvei5hdXRoLmRvbWFpbi5Sb2xlUgRyb2xlE
  lQKDWN1c3RvbV9jbGFpbXMYAyADKAsyLy52b3ouYXV0aC5kb21haW4uVG9rZW5SZXF1ZXN0LkN1c3RvbUNsYWltc0VudHJ5Ugxjd
  XN0b21DbGFpbXMSOAoIYXVkaWVuY2UYBCABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWVSCGF1ZGllbmNlEj0KC3Zhd
  Wx0X3Rva2VuGAUgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlUgp2YXVsdFRva2VuGj8KEUN1c3RvbUNsYWltc0Vud
  HJ5EhAKA2tleRgBIAEoCVIDa2V5EhQKBXZhbHVlGAIgASgJUgV2YWx1ZToCOAEiYAoRQ2hpbGRUb2tlblJlcXVlc3QSIQoMcGFyZ
  W50X3Rva2VuGAEgASgJUgtwYXJlbnRUb2tlbhIoChBuZWVkc192YXVsdF9hdXRoGAIgASgIUg5uZWVkc1ZhdWx0QXV0aCIiCgpUb
  2tlblJlcGx5EhQKBXRva2VuGAEgASgJUgV0b2tlbiodCgRSb2xlEgsKB1NlcnZpY2UQABIICgRVc2VyEAEy9AEKBEF1dGgSUgoNR
  2V0Q2hpbGRUb2tlbhIiLnZvei5hdXRoLmRvbWFpbi5DaGlsZFRva2VuUmVxdWVzdBobLnZvei5hdXRoLmRvbWFpbi5Ub2tlblJlc
  Gx5IgASTgoOR2V0UGFyZW50VG9rZW4SHS52b3ouYXV0aC5kb21haW4uVG9rZW5SZXF1ZXN0Ghsudm96LmF1dGguZG9tYWluLlRva
  2VuUmVwbHkiABJICghHZXRUb2tlbhIdLnZvei5hdXRoLmRvbWFpbi5Ub2tlblJlcXVlc3QaGy52b3ouYXV0aC5kb21haW4uVG9rZ
  W5SZXBseSIAYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.wrappers.WrappersProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}