// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package voz.auth.domain.Auth



sealed trait Role extends _root_.com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = Role
  def isService: Boolean = false
  def isUser: Boolean = false
  def companion: _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[Role] = voz.auth.domain.Auth.Role
}

object Role extends _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[Role] {
  implicit def enumCompanion: _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[Role] = this
  @SerialVersionUID(0L)
  case object Service extends Role {
    val value = 0
    val index = 0
    val name = "Service"
    override def isService: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object User extends Role {
    val value = 1
    val index = 1
    val name = "User"
    override def isUser: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends Role with _root_.com.trueaccord.scalapb.UnrecognizedEnum
  
  lazy val values = scala.collection.Seq(Service, User)
  def fromValue(value: Int): Role = value match {
    case 0 => Service
    case 1 => User
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = AuthProto.javaDescriptor.getEnumTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = AuthProto.scalaDescriptor.enums(0)
}